### ISSUE TITLE
Why is encryption of kernel bitcode necessary before caching on NVIDIA hardware?

### ISSUE THREAD

**Issue by TomClabault** [GPUOpen-LibrariesAndSDKs/HIPRT#11]
On NVIDIA hardware, kernel bitcode is encrypted before being cached to disk ([Compiler.cpp:668](https://github.com/GPUOpen-LibrariesAndSDKs/HIPRT/blob/main/hiprt/impl/Compiler.cpp#L668)).

The overhead is quite significant and cannot be avoided for BVH building kernels where caching behavior is hardcoded to true ([Compiler.cpp:86](https://github.com/GPUOpen-LibrariesAndSDKs/HIPRT/blob/main/hiprt/impl/Compiler.cpp#L86) from [LBVHBuilder.h:204](https://github.com/GPUOpen-LibrariesAndSDKs/HIPRT/blob/main/hiprt/impl/LbvhBuilder.h#L204) for example).

Why is encryption necessary on NVIDIA hardware but not AMD?

**Comment by meistdan** [comment]
While AMD Bitcode is a binary format, the NVIDIA PTX is assembly-like language. At the time when HIPRT was not open-source, we did want to expose the implementation; therefore, we encrypted the PTX. I guess we can disable it as the source codes are public anyway.
