### ISSUE TITLE
Potential Bug in LBVH code

### ISSUE THREAD

**Issue by Niravaana** [GPUOpen-LibrariesAndSDKs/HIPRT#15]
It seems the LBVH code might have a bug, 
the function https://github.com/GPUOpen-LibrariesAndSDKs/HIPRT/blob/5ffcea6322519b25500f6d3140bbb42dd06fb464/hiprt/impl/MortonCode.h#L281
the condition should be

     if (i < 0 || j >= n) return ~0ull; 

This is code in **findHighestBitDifference()** which is called from **findParent()** like below 

     if ( i == 0 && j == n ) return InvalidValue;
    if ( i == 0 || ( j != n && findHighestDifferentBit( j - 1, j, n, sortedMortonCodeKeys ) <   findHighestDifferentBit( i - 1, i, n, sortedMortonCodeKeys ) ) ) 

So the parameter j can never be negative value as j is i + 1 always and i starts at 0. While i starts with 0 so for the first thread i- 1 can be negative value which needs to be handled.

**Comment by meistdan** [comment]
Isn't this handled by `i == 0`?

**Comment by Niravaana** [comment]
Hmm yeah seems like this will work here.
Thanks for checking out.

**Comment by Niravaana** [comment]
You are right if ( i == 0 && j == n ) return InvalidValue; 
Should handle is though 

if ( j < 0 || j >= n ) return ~0ull;  

The first j should be i right ?

Its bit confusing.

**Comment by meistdan** [comment]
I mean that it won't be negative because `i == 0` is handled in the `findParent` before calling `findHighestDifferentBit`, but yes, ` if (i < 0 || j >= n )` makes more sense.

**Comment by Niravaana** [comment]
You are right i will never be negative. Thanks for the clarification :)
