### ISSUE TITLE
Usage of hiprtTraversalHintShadowRays & hiprtTraversalHintReflectionRays

### ISSUE THREAD

**Issue by TomClabault** [GPUOpen-LibrariesAndSDKs/HIPRT#19]
How are reflection and shadow rays defined here?

Is a shadow ray any ray that has a given `Tmax` <<< MAX_FLOAT? And reflection rays are rays with no `Tmax`?

Also, how do these hints work under the hood? What does the hardware accomplish with them?

**Comment by meistdan** [comment]
There is no any definition of shadow or reflected rays. For shadow rays, we use the any-hit traversal object, assuming that we stop after finding any first intersection. For reflected rays, it's not that clear, but you can, for example assume that the origin is on a surface.

I cannot expose the implementation details of these hints, but according my experience, the default hint was always better than two others.

**Comment by TomClabault** [comment]
>  but according my experience, the default hint was always better than two others.

I'll have a try myself and see the performance but that's unfortunate.
