### ISSUE TITLE
Building on Linux

### ISSUE THREAD

**Issue by ib00** [GPUOpen-LibrariesAndSDKs/HIPRT#2]
Building on Linux doesn't work.

==== Building hiprt02003 (debug_x64) ====
BatchBuilder.cpp
In file included from ../hiprt/impl/BatchBuilder.h:29,
                 from ../hiprt/impl/BatchBuilder.cpp:26:
../hiprt/impl/Context.h:26:10: fatal error: Orochi/Orochi.h: No such file or directory
   26 | #include <Orochi/Orochi.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.

Orochi exists in the contrib/ directory.

**Comment by ScatteredRay** [comment]
FWIW, I don't get the same issue locally, the include seems to be set in the premake here:
```
    externalincludedirs { "./contrib/Orochi/" }
```
Are you sure the Orochi submodule is properlly cloned?

Perhaps further reproduction instructions will be helpful.

**Comment by ib00** [comment]
Your fork compiles fine for me, but the official repository doesn't.

**Comment by ScatteredRay** [comment]
Continuing, this is the same error I get when I don't successfully clone submodules. I'd say just do a 'git submodule update --init' but as I submitted in my other bug: https://github.com/GPUOpen-LibrariesAndSDKs/HIPRT/issues/3 that fails right now.

**Comment by RichardGe** [comment]
I just removed the private submodule.
My understanding is that it was what was causing this Linux build error.
I'll assume this is fixed with:
https://github.com/GPUOpen-LibrariesAndSDKs/HIPRT/pull/5
Please if you still have building error, re-open the ticket, or create a new one.

**Comment by ib00** [comment]
Thank you! The main branch compiles fine now on linux.
