### ISSUE TITLE
Support status of CNDA1 (mi100)

### ISSUE THREAD

**Issue by IMbackK** [GPUOpen-LibrariesAndSDKs/HIPRT#24]
Is mi100/gfx908/cdna1 supported by hiprt? The changelog mentions mi200 and mi60 but not mi100 and https://gpuopen.com/hiprt/ mentions only rdna.

**Comment by meistdan** [comment]
We haven't tested HIPRT on MI100 but it should run as well.

**Comment by IMbackK** [comment]
i see, i will run the unit tests and report back.

**Comment by IMbackK** [comment]
```
[==========] 38 tests from 2 test cases ran. (64983 ms total)
[  PASSED  ] 38 tests.
../dist/bin/Release/unittest64 --width=512 --height=512    64.39s user 0.94s system 100% cpu 1:05.07 total
```

Looks ok!, maybe document the support somewhere.
