### ISSUE TITLE
hiprtBuildGeometry() expects (hardcoded) the BVH building kernels to be in "../hiprt/impl/XXX.h"

### ISSUE THREAD

**Issue by TomClabault** [GPUOpen-LibrariesAndSDKs/HIPRT#7]
When bitcodes haven't been precompiled at HIPRT building time, `hiprtBuildGeometry()` will try to compile the BVH building kernels on the fly. This compilation step requires the path to the kernel file which seems to be [hardcoded to](https://github.com/GPUOpen-LibrariesAndSDKs/HIPRT/blob/main/hiprt/impl/LbvhBuilder.h#L205) `"../hiprt/impl/BvhBuilderKernels.h"` (example of the `LbvhBbuilder`).

This requires a project using HIPRT as a dependency to provide the `hiprt/impl` folder one level above the working directory which may not always be the case. One simple example would be a CMake setup fetching and building HIPRT in a `build/` directory. The `hiprt/impl` folder, in this case, would be found somewhere in a subdirectory of `build/` but definitely not in the root directory of the project, one level above `build/`.

Precompiled bitcodes could be a solution to that since the compiler seems to be looking for the fat binary in the working directory instead of one level above. This would however be more of a circumvention of the issue rather than a proper solution.

What's the best way to deal with this issue?

**Comment by meistdan** [comment]
This is a good point. We will address this issue.
